config/routes.rb
Rails.application.routes.draw do
  resources :receivers
  resources :senders
  resources :negotiations
  resources :requests

  devise_for :users, controllers: { registrations: "registrations"}
  

   root 'pages#home'

   get 'dashboard' => "pages#dashboard"
   

end

app/models/receiver.rb
class Receiver < ActiveRecord::Base
	extend FriendlyId
	friendly_id :stuff, use: :slugged
	validates_presence_of :stuff
	validates_presence_of :source_address
	validates_presence_of :destination_address
	validates_presence_of :from
	validates_presence_of :to
	validates_presence_of :user_id
	belongs_to :user
	has_attached_file :image,
	:style => { :medium => "300x300>", :thumb => "100x100>" },
	:storage => :s3,
	:bucket  => ENV['S3_BUCKET_NAME'],
	:s3_credentials => {
		:access_key_id => ENV['AWS_ACCESS_KEY_ID'],
		:secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
		},
		:s3_permissions => 'private',
		:url => ":s3_domain_url"
		validates :image, presence: true
		validates :description, presence: false

	validates_attachment_content_type :image, 
	content_type:  /^image\/(png|gif|jpeg)/,
	message: "Зөвхөн зураг оруулна уу!"
	validates :image, attachment_presence: true
	


	geocoded_by :source_address, :latitude => :latitude1, :longitude => :longitude1
	geocoded_by :destination_address, :latitude => :latitude2, :longitude => :longitude2
	after_validation :geocode

	has_many :requests, dependent: :destroy
end

app/controllers/receivers_controller.rb
class ReceiversController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_receiver, only: [:show, :edit, :update, :destroy]

  # GET /receivers
  # GET /receivers.json
  def index
    @receivers = Receiver.all
  end

  # GET /receivers/1
  # GET /receivers/1.json
  def show
    @requests = @receiver.requests
    @request = Request.new
  end

  # GET /receivers/new
  def new
    @receiver = Receiver.new
  end

  # GET /receivers/1/edit
  def edit
    authorize! :manage, @receiver
  end

  # POST /receivers
  # POST /receivers.json
  def create
    @receiver = current_user.receivers.new(receiver_params)

    respond_to do |format|
      if @receiver.save
        format.html { redirect_to @receiver, notice: 'Receiver was successfully created.' }
        format.json { render :show, status: :created, location: @receiver }
      else
        format.html { render :new }
        format.json { render json: @receiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receivers/1
  # PATCH/PUT /receivers/1.json
  def update
    respond_to do |format|
      if @receiver.update(receiver_params)
        format.html { redirect_to @receiver, notice: 'Receiver was successfully updated.' }
        format.json { render :show, status: :ok, location: @receiver }
      else
        format.html { render :edit }
        format.json { render json: @receiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receivers/1
  # DELETE /receivers/1.json
  def destroy
    @receiver.destroy
    respond_to do |format|
      format.html { redirect_to receivers_url, notice: 'Receiver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receiver
      @receiver = Receiver.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receiver_params
      params.require(:receiver).permit(:stuff, :description, :source_address, :destination_address, :from, :to, :phone, :mail, :fee, :image)
    end
end

app/helpers/receivers_helper.rb
module ReceiversHelper
end

app/views/receivers/_form.html.erb
<%= simple_form_for(@receiver) do |f| %>
  <%= f.error_notification %>

  
    <%= f.input :stuff, required: true, autofocus: true, :label => "Илгээх зүйл", placeholder: "Жишээ : Бичиг баримт, CD, Гар утас...", input_html: {class: "form-zontrol"} %>
    <%= f.input :image,required: false,  :label => "Зураг"%>
    <%= f.input :description, :label => "Дэлгэрэнгүй тайлбар", placeholder: "Жишээ : Иргэний үнэмлэх яаралтай дайж авчруулах хэрэгтэй байна." , input_html: {class: "form-zontrol"} %>
    <%= f.input :source_address, required: true, :label => "Хаанаас", placeholder: "Tokyo, Taipei, Ulaanbaatar..." , input_html: {class: "form-zontrol"} %>
    <%= f.input :destination_address, required: true, :label => "Хаашаа", placeholder: "Google maps дээрхи хаяг байвал оновчтой дүрслэнэ." , input_html: {class: "form-zontrol"}  %>
    <%= f.input :from, required: true ,:label => "Хэднээс",  input_html: {class: "form-date"} %>
    <%= f.input :to, required: true , :label => "Хэдийд", input_html: {class: "form-date"} %>
    <%= f.input :phone, :label => "Утас", placeholder: "99887766 эсвэл +976-11-99887766" , input_html: {class: "form-zontrol"}  %>
    <%= f.input :mail , :label => "Майл хаяг", placeholder: "" , input_html: {class: "form-zontrol"} %>
    <%= f.input :fee ,:label => "Төлөх хөлс", placeholder: "1000₮ 3$ " , input_html: {class: "form-zontrol"} %>
    
    
  </div>
<center>
  <div class="form-actions">
    <%= f.button :submit, "Дуусгах" %>
  </div>
<% end %>
</center>

app/views/receivers/edit.html.erb
<center>
	<h2 class="text-center"> Хүргүүлэх хүсэлт өөрчлөх </h2>
<br>
<%= render 'form' %>
<center><br>
<%= link_to 'Буцах', receivers_path %> | 
<%= link_to 'Үзэх', @receiver,:method => :get %> | 
<%= link_to 'Устгах', receiver_path(@receiver), data: { confirm: "Та итгэлтэй байна уу?" }, :method => :delete %> 
<center>
</center>

app/views/receivers/index.html.erb
<h1>Хүлээн авагчдын жагсаалт</h1>

<table class="table">
  <thead>
    <tr>
      <th>Хэн </th>
      <th>Юуг </th>
      <th>Хаанаас </th>
      <th>Хаашаа </th>
      <th>Хэднээс</th>
      <th>Хэднийд</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    
    <% @receivers.each do |receiver| %>
      <tr>
        <% if current_user %>
        <td><%= gravatar_tag receiver.user.email, size: 30 %> <%= receiver.user.name %> </td>
        <% else %>
        <td><%= receiver.user.name %> </td>
        <% end %>
        <td><%= receiver.stuff %></td>
        <td><%= receiver.source_address %></td>
        <td><%= receiver.destination_address %></td>
        <td><%= receiver.from %></td>
        <td><%= receiver.to %></td>
        
        <td><ul class="list-group">
          
            
            <%= link_to 'Дэлгэрэнгүй  ', receiver_path(receiver.id),:method => :get %><span class="badge"><%= receiver.requests.count %></span>
          </li>
        
        </ul></td>
        
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user %>
<i class="fa fa-plus fa-lg"><%= link_to 'нэмэх', new_receiver_path %></i>
<% end %>

app/views/receivers/new.html.erb
<center>

<h2 class="text-center"> Хүргүүлэх хүсэлт гаргах </h2>
<br>

<%= render 'form' %>

<%= link_to 'Буцах', receivers_path %>
</center>

app/views/receivers/show.html.erb
 <div class="row">
  <div class="col-md-3">
    <div class="list-group">
      <a class="list-group-item" href=""><i class="fa fa-home fa-fw"></i>&nbsp; Юу: <%= @receiver.stuff %></a>
      <a class="list-group-item" href="#"><i class="fa fa-picture-o fa-fw"></i>&nbsp; Зураг: <%= image_tag @receiver.image.url(:original), class: "img-responsive" %></a>
      <a class="list-group-item" href="#"><i class="fa fa-pencil fa-fw"></i>&nbsp; Тайлбар: <%= @receiver.description %> </a>
      <a class="list-group-item" href="#"><i class="fa fa-home fa-fw"></i>&nbsp; Хаанаас: <%= @receiver.source_address %> </a>
      <a class="list-group-item" href="#"><i class="fa fa-plane fa-fw"></i>&nbsp; Хаашаа: <%= @receiver.destination_address %><div id="map-canvas2" style="width: 230px; height:230px;" ></div></a>
      <a class="list-group-item" href="#"><i class="fa fa-calendar fa-fw"></i>&nbsp; Хэднээс: <%= @receiver.from %> </a>
      <a class="list-group-item" href="#"><i class="fa fa-calendar fa-fw"></i>&nbsp; Хэдийд: <%= @receiver.to %> </a>
      <a class="list-group-item" href="#"><i class="fa fa-phone fa-fw"></i>&nbsp; Утас: <%= @receiver.phone %> </a>
      <a class="list-group-item" href="#"><i class="fa fa-envelope-o fa-fw"></i>&nbsp; Майл: <%= @receiver.mail %> </a>
      <a class="list-group-item" href="#"><i class="fa fa-usd fa-fw"></i>&nbsp; Олгох хөлс: <%= @receiver.fee %>   </a>
      
    </div>
  </div>  



<div class="col-md-9">

  <h3>Хүргэх саналууд</h3>
  <% if current_user %>
  <h5>Шинэ санал</h5>
  <%= render "requests/form" %>
  <h5>Саналууд:</h5>
  <%= render @requests %>
  <% else %>
  <p>Сайтруу нэвтэрсний дараа санал оруулна уу?</p>
  <% end %>
</div>

</div>


<div id="map-canvas1" style="width: 230px; height:230px;" > </div>

<script type="text/javascript">
function initialize() {

  var dest = {lat: <%= @receiver.latitude2 %>, lng: <%= @receiver.longitude2 %>};


  var mapOptions2 = {
    center: dest,
    zoom: 8
  };


  var map2 = new google.maps.Map(document.getElementById('map-canvas2'), mapOptions2);


  var marker2 = new google.maps.Marker({
    position:dest,
    map: map2
  });


}
google.maps.event.addDomListener(window, 'load', initialize);
$(document).bind("projectLoadComplete", initialize);
</script>