config/routes.rb
Rails.application.routes.draw do
  resources :receivers
  resources :senders
  resources :negotiations
  resources :requests

  devise_for :users, controllers: { registrations: "registrations"}
  

   root 'pages#home'

   get 'dashboard' => "pages#dashboard"
   

end

app/views/pages/_receivers.html.erb
<table class="table table-condensed">
      <thead>

        <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-62016890-1', 'auto');
  ga('send', 'pageview');

</script>
        <tr>
          <th>Юуг</th>
          <th>Хаанаас</th>
          <th>Хаашаа</th>
          <th></th>
          
        </tr>
      </thead>
      <tbody>
        <% @receivers.each do |receiver| %>
        <tr>
          <td><%= receiver.stuff %></td>
          <td><%= receiver.source_address %></td>
          <td><%= receiver.destination_address %></td>
          <td><%= link_to 'засах', edit_receiver_path(receiver) %>
          
          
        </tr>
        <% end %>

      </tbody>
    </table>

app/views/pages/_senders.html.erb
<table class="table table-condensed">
      <thead>

        <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-62016890-1', 'auto');
  ga('send', 'pageview');

</script>
        <tr>
          <th>Хаанаас</th>
          <th>Хаашаа</th>
          <th>Ирэх өдөр</th>
          
          <th></th>
        </tr>
      </thead>
      <tbody>
      	<% @senders.each do |sender| %>
        <tr>
          <td><%= sender.source_address %></td>
          <td><%= sender.destination_address %></td>
          <td><%= sender.arrival %></td>
          <td><%= link_to 'засах', edit_sender_path(sender) %>
          
          
          
          

        </tr>
        <% end %>

      </tbody>
    </table>

app/views/pages/about.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<iframe width="560" height="315" src="https://www.youtube.com/embed/rTP1eMfI5Bs" frameborder="0" allowfullscreen></iframe>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-62016890-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/pages/dashboard.html.erb
<div class="row">
  <h1 class="text-center">Удирдах самбар</h1>

  <div class="col-md-6">
    <h4 class="text-center">
      Миний хүргэлтүүд <%= link_to "Хүргэлт нэмэх", new_sender_path, class: "btn btn-info btn-sm" %>
    </h4>
    <%= render "senders" %>
  </div>

  <div class="col-md-6">
    <h4 class="text-center">
      Миний хүргүүлэх хүсэлтүүд <%= link_to "Хүсэлт нэмэх", new_receiver_path, class: "btn btn-info btn-sm" %>
    </h4>
    <%= render "receivers" %>
  </div>

  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-62016890-1', 'auto');
  ga('send', 'pageview');

</script>


</div>

app/views/pages/home.html.erb
<div class="container">
<section class="container-fluid" id="section1">
  	<h2 class="text-center v-center1">Хүн бүр хүргэгч
    <h2 class="text-center v-center">  <i class='fa fa-rocket '> Хүргэлт.орг</i>
     
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-62016890-1', 'auto');
  ga('send', 'pageview');
</script>

     </h2>

  	<div class="container">
      <div class="row">
          <div class="col-sm-4">
            <div class="row">
              <div class="col-sm-10 col-sm-offset-2 text-center"><h3>Найдвартай</h3><p>Amazon Web Services, Heroku зэрэг шалгарсан хостингууд дээр суурилсан</p><i class="fa fa-database faa-tada animated-hover fa-4x faa-slow"></i>
</i></div>
            </div>
          </div>
          <div class="col-sm-4 text-center">
            <div class="row">
              <div class="col-sm-10 col-sm-offset-1 text-center"><h3>Хялбар</h3><p>Бодит хэрэгцээн дээр тулгуурлаж хэн ч ойлгоод ашиглахаар загварчлав.</p><i class="fa fa-user faa-pulse animated-hover fa-4x faa-slow"></i></div> 
            </div>
          </div>
          <div class="col-sm-4 text-center">
            <div class="row">
              <div class="col-sm-10 text-center"><h3>Үнэгүй</h3><p>Ашиглахад үнэ төлбөргүй. Магадгүй үргэлж төлбөргүй байх болно</p><i class="fa fa-money faa-float animated-hover fa-4x faa-slow"></i></div>
            </div>
          </div>
      </div><!--/row-->
    <div class="row"><br></div>
  </div><!--/container-->
</section>

<section class="container-fluid" id="section2">
  <div class="row">
  	<div class="col-sm-8 col-sm-offset-2 text-center">
        <h1>Яг юу юм вэ?</h1>
        <br>
		<p class="lead">Таньд ямар нэг зүйлийг илгээх, дайх болон авчруулах шаардлага гардаг уу? Шуудан, DHL, Fedex хэтэрхий үнэтэй байна уу? Тэгвэл та манай сайтаас хүссэн зүйлийг тань харьцангуй боломжын үнээр аваад ирэх өөр хэн нэгнийг олж яагаад болохгүй гэж. Бүртгүүлээд, хүлээн авагч/илгээгчээ сонгоод үнээ тохиролц. Ердөө л энэ...</p>
        <br> 
      	
      	
    </div>
  </div>
</section>


<section class="container-fluid" id="section6">
	<h2 class="text-center">Хэрхэн ашиглах вэ?</h2>
    <p class="text-center lead"><iframe src="https://player.vimeo.com/video/125393619?color=168ccc&title=0&byline=0&portrait=0" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></p>
    
</section>

        

<section class="container-fluid" id="section2">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 text-center">
        
        <center><li>Хүргэгч<div class="circle-image"></div><p class="lead">Хэн ч хүргэгч/дайгч байж болно. Гагцхүү хаанаас хаашаа, очих өдөр болон холбогдох мэдээллээ үлдээх хэрэгтэй. Эсвэл хүсэлт гаргагчыг олоод саналаа тавь. Зүгээр нэг явахаар замаараа хүнд юмыг нь хүргэж буян болонгоо хэдэн цаас олчиход сайхан биш гэжүү? :)</p></li>
        

        
        <center><li>Хүлээн авагч<div class="circle-image1"></div><p class="lead">Хүн болгонд хүргэлтийн үйлчилгээ хэрэгтэй байдаг. Одоо байгаа хүргэлтийн шийдлүүд нь удаан, уян хатан бус байх нь олонтаа. Тэгвэл та Юуг-Хаанаас-Хаашаа-Хэднээс-Хэдийд асуултуудад хариулснаар хурдан, найдвартай, харьцангуй хямд хүргэлтийн үйлчилгээг авах болох боломжтой. </p</li>

   
        <br> 
        
        
    </div>
  </div>
</section>





<footer id="footer">
  <div class="container">
    <div class="row">    
      <div class="col-xs-6 col-sm-6 col-md-3 column">          
          <h4>Мэдээлэл</h4>
          <ul class="nav">
            <li><a href="#">Блог</a></li>
            <li><a href="#">Үйлчилгээ</a></li>
            <li><a href="#">Хөгжүүлэгчид</a></li>
            
          </ul> 
        </div>
      <div class="col-xs-6 col-md-3 column">          
          <h4>Биднийг дагах</h4>
          <ul class="nav">
            <li><a href="#">Twitter</a></li>
            <li><a href="https://www.facebook.com/hurgeltorg">Facebook</a></li>
            <li><a href="#">Google+</a></li>
            
          </ul> 
      </div>
      <div class="col-xs-6 col-md-3 column">          
          <h4>Холбоо барих</h4>
          <ul class="nav">
            <li><a href="#">Бидний тухай</a></li>
            <li><a href="#">Байршил</a></li>
            <li><a href="mailto:contact@hurgelt.org?subject=Хамтарч ажиллах санал">Хамтран ажиллах</a></li>
            <li><a href="#">Ажлын байр</a></li>
          </ul> 
      </div>
      <div class="col-xs-6 col-md-3 column">          
          <h4>Хууль эрх зүй</h4>
          <ul class="nav">
            <li><a href="#">Гаалиар хориглосон бараа</a></li>
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">Terms &amp; Conditions</a></li>
          </ul> 
      </div>
    </div><!--/row-->
  </div>
</footer>

</div>
</div>
</div>

<body>

  