config/routes.rb
Rails.application.routes.draw do
  resources :receivers
  resources :senders
  resources :negotiations
  resources :requests

  devise_for :users, controllers: { registrations: "registrations"}
  

   root 'pages#home'

   get 'dashboard' => "pages#dashboard"
   

end

app/models/sender.rb
class Sender < ActiveRecord::Base
	
	validates_presence_of :source_address
	validates_presence_of :destination_address
	validates_presence_of :arrival
	validates_presence_of :phone
	validates_presence_of :mail
	validates_presence_of :user_id
	belongs_to :user
	
	geocoded_by :source_address, :latitude => :latitude, :longitude => :longitude
	geocoded_by :destination_address, :latitude => :latitude2, :longitude => :longitudde2
	
	def update_coordinates
  		geocode
  		[latitude, longitude, latitude2, longitudde2]
	end

	after_validation :geocode  

	has_many :negotiations, dependent: :destroy
	
end

app/controllers/senders_controller.rb
class SendersController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_sender, only: [:show, :edit, :update, :destroy]

  # GET /senders
  # GET /senders.json
  def index
    @senders = Sender.all
  end

  # GET /senders/1
  # GET /senders/1.json
  def show
    #@sender = Sender.find(params[:id])
    @negotiations = @sender.negotiations
    @negotiation = Negotiation.new

  end

  # GET /senders/new
  def new
    @sender = Sender.new
  end

  # GET /senders/1/edit
  def edit
    authorize! :manage, @sender
  end

  # POST /senders
  # POST /senders.json
  def create
    @sender = current_user.senders.new(sender_params)

    respond_to do |format|
      if @sender.save
        format.html { redirect_to @sender, notice: 'Sender was successfully created.' }
        format.json { render :show, status: :created, location: @sender }
      else
        format.html { render :new }
        format.json { render json: @sender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /senders/1
  # PATCH/PUT /senders/1.json
  def update
    authorize! :manage, @sender
    respond_to do |format|
      if @sender.update(sender_params)
        format.html { redirect_to @sender, notice: 'Sender was successfully updated.' }
        format.json { render :show, status: :ok, location: @sender }
      else
        format.html { render :edit }
        format.json { render json: @sender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /senders/1
  # DELETE /senders/1.json
  def destroy
    authorize! :manage, @sender
    # ene lineiig nemev!
    @sender = Sender.find(params[:id])
    #
    @sender.destroy

    respond_to do |format|
      format.html { redirect_to senders_url, notice: 'Sender was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sender
      @sender = Sender.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sender_params
      params.require(:sender).permit(:source_address, :destination_address, :description, :arrival, :phone, :mail, :fee)
    end
end

app/helpers/senders_helper.rb
module SendersHelper
end

app/views/senders/_form.html.erb
<center><%= simple_form_for(@sender) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :source_address, required: true, :label => "Хаанаас", placeholder: "Tokyo, Taipei, Ulaanbaatar..." , input_html: {class: "form-zontrol"} %>
   <%= f.input :destination_address, required: true, :label => "Хаашаа", placeholder: "Google maps дээрхи хаяг байвал оновчтой дүрслэнэ." , input_html: {class: "form-zontrol"}  %>
    <%= f.input :description, :label => "Дэлгэрэнгүй тайлбар", placeholder: "" , input_html: {class: "form-zontrol"} %>
    <%= f.input :arrival, required: true ,:label => "Очих өдөр",  input_html: {class: "form-date"} %>
    


    <%= f.input :phone, :label => "Утас", placeholder: "99887766 эсвэл +976-11-99887766" , input_html: {class: "form-zontrol"}  %>
    <%= f.input :mail , :label => "Майл хаяг", placeholder: "" , input_html: {class: "form-zontrol"} %>
    <%= f.input :fee ,:label => "Хүсэж буй хөлс", placeholder: "1000₮/кг 3$/kg гэх мэт " , input_html: {class: "form-zontrol"} %>
    
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Үүсгэх" %>
  </div>
<% end %>
</center>

app/views/senders/edit.html.erb
<center><h2 class="text-center"> Хүргэлтийн мэдээлэл засах </h2>
<br>
<%= render 'form' %>

<%= link_to 'Буцах', senders_path %> |
<%= link_to 'Харах', @sender,:method => :get %> |
<%= link_to 'Устгах', sender_path(@sender), data: { confirm: "Та итгэлтэй байна уу?" }, :method => :delete %> 
<center>

app/views/senders/index.html.erb
<h1>Хүргэгчдийн жагсаалт</h1>

<table class="table">
  <thead>
    <tr>
      <th>Нэр</th>
      <th>Хаанаас</th>
      <th>Хаашаа</th>
      <th>Ирэх өдөр</th>
      <th>Хүсэж буй хөлс</th>
      <th></th>
      
    </tr>
  </thead>

  <tbody>
    <% @senders.each do |sender| %>
      <tr>
        
        <% if current_user %>
        <td> <%= gravatar_tag sender.user.email, size: 30 %> <%= sender.user.name %></td>
        <% else %>
        <td><%= sender.user.name %></td>
        <% end %>
        
        <td><%= sender.source_address %></td>
        <td><%= sender.destination_address %></td>
        <td><%= sender.arrival %></td>
        <td><%= sender.fee %></td>
        <td>
          <%= link_to 'Дэлгэрэнгүй', sender_path(sender.id), :method => :get %> <span class="badge"><%= sender.negotiations.count %></span></td>
          
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user %>
<i class="fa fa-plus fa-lg"><%= link_to 'нэмэх', new_sender_path %></i>
<% end %>

app/views/senders/new.html.erb
<center>
<h2 class="text-center"> Хүргэлтийн мэдээлэл оруулах</h2>
<%= render 'form' %>
<br>
<%= link_to 'Буцах', senders_path %>
</center>

app/views/senders/show.html.erb
<script type="text/javascript">
      function initialize() {
        
        var dest = {lat: <%= @sender.update_coordinates[2] %>, lng: <%= @sender.update_coordinates[3] %>};
        
        var mapOptions2 = {
          center: dest,
          zoom: 8
        };
        
        
        var map2 = new google.maps.Map(document.getElementById('map-canvas2'), mapOptions2);
        
        
        var marker2 = new google.maps.Marker({
          position:dest,
          map: map2
        });
      }
      google.maps.event.addDomListener(window, 'load', initialize);
      $(document).bind("projectLoadComplete", initialize);
    </script>

    <div class="row">
      <div class="col-md-3">
        <div class="list-group">
          <a class="list-group-item" href=""><i class="fa fa-home fa-fw"></i>&nbsp; Хаанаас: <%= @sender.source_address %></a>
          <a class="list-group-item" href="#"><i class="fa fa-plane fa-fw"></i>&nbsp; Хаашаа: <%= @sender.destination_address %> <div id="map-canvas2" style="width:230px; height:230px;"></div></a>
          <a class="list-group-item" href="#"><i class="fa fa-pencil fa-fw"></i>&nbsp; Тайлбар: <%= @sender.description %> </a>
          <a class="list-group-item" href="#"><i class="fa fa-calendar fa-fw"></i>&nbsp; Очих өдөр: <%= @sender.arrival %> </a>
          <a class="list-group-item" href="#"><i class="fa fa-phone fa-fw"></i>&nbsp; Утас: <%= @sender.phone %> </a>
          <a class="list-group-item" href="#"><i class="fa fa-envelope-o fa-fw"></i>&nbsp; Майл: <%= @sender.mail %> </a>
          <a class="list-group-item" href="#"><i class="fa fa-usd fa-fw"></i>&nbsp; Ачаа/кг үнэлгээ: <%= @sender.fee %> </a>

          
        </div>
</div>

         

<div class="col-md-9">

<h3> Тохиролцох талбар</h3>
<% if current_user %>
<h5>Шинэ санал</h5>
<%= render "negotiations/form" %>
<h5>Саналууд:</h5>
<%= render @negotiations %>
<% else %>
  <p>Сайтруу нэвтэрсний дараа санал оруулна уу?</p>
<% end %>
</div>



</div>


<div id="map-canvas2"></div>


 