config/routes.rb
Rails.application.routes.draw do
  resources :receivers
  resources :senders
  resources :negotiations
  resources :requests

  devise_for :users, controllers: { registrations: "registrations"}
  

   root 'pages#home'

   get 'dashboard' => "pages#dashboard"
   

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header" >
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    
      <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-62016890-1', 'auto');
  ga('send', 'pageview');
ga(‘set’, ‘&uid’, {{USER_ID}}); // Set the user ID using signed-in user_id.
</script>
      
      <%= link_to "<i class='fa fa-rocket fa-spin'></i> Хүргэлт.орг".html_safe, root_path,  class: "navbar-brand" %>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav ">
        <li><%= link_to "Хүргэх", senders_path %></li>
        <li><%= link_to "|" %></li>
        <li><%= link_to "Хүлээн авах", receivers_path %></li>
        
       
      </ul>

      
      <ul class="nav navbar-nav navbar-right">
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Хайлт">
        </div>
        <button type="submit" class="btn btn-default">Хайх</button>
      </form> -->
      
        
        <% if current_user %>
        
        <li><%= link_to "Тохиргоо", edit_user_registration_path %></li>
        <li><%= link_to "Самбар", dashboard_path %></li>



        <li><%= link_to "Гарах", destroy_user_session_path, method: :delete %></li>
       
       



        <%else %>
        
        <li><%=link_to "Нэвтрэх", new_user_session_path %></li>
        <li><%=link_to "Бүртгүүлэх", new_user_registration_path %></li>
        <%end%>
       
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head > <link rel="shortcut icon" href="myIcon.ico" type="image/x-icon" />

  <title>Хүргэлт хялбарчлагдав</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 
  <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDLTxrEcDNc0Yc5ZWZxC490SjQLJurigeE">
   </script>

   <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-62016890-1', 'auto');
  ga('send', 'pageview');

</script>
</head>

<body>
<%= render "layouts/header" %>
<div class="container">
<% flash.each do |type, message| %>
<div class = "alert alert-info fade-in">
<button class="close" data-dismiss="alert">x</button>	
<%= message %>
</div>
<% end %> 




<%= yield %>
</div>


</body>
</html>